### ISSUE TITLE
[Bug] Twitch Plays Pokemon Display Issue

### ISSUE THREAD

**Issue by guy6020665** [Cysha/pokelink-web#6]
Twitch Plays Pokemon theme does not display pokemon if they have less than 4 moves.

In function getViewbox(moveName). 
Attempts to read length of moveName, but moveName is undefined.

Affects at least Fire Red/Leaf Green.

**Comment by NoelDavies** [comment]
Yes, this theme was a demo. And is not finished - this is going to be removed soon. Sorry!
